### ISSUE TITLE
Output to Confirm package was installed successfully

### ISSUE THREAD

**Issue by pgensler** [r-lib/remotes#115]
It would be nice to have a simple line outputted stating that package x was installed successfully after all deps and what not have been installed. Maybe this is now possible with the glue package?
This would make verifying packages installing correctly in containers much more verifiable, as you could easily tell which packages succeeded, and which ones failed.

**Comment by gaborcsardi** [comment]
We could try to load the package after the installation, but this is actually trickier than it sounds, because 
1. the package might be loaded already, so we need to unload it, which is tricky, because other packages might depend on it.
2. it is a side effect for the current session, and users might want to avoid this.

Ideally we would try to load the installed  package in another session, but that  is tricky as  well, and we  would need to use the callr package.

This is definitely sg that we should  have in the full fledge pkgman package.

For your use case, inside the container, can you just try to do `library(<package>)` after the  installation, to see if it works?

**Comment by pgensler** [comment]
Agreed, I do think `pkgman` is the best place for this functionality. The main reason for this is to see inside the build scripts of DockerHub or Travis  if a package was installed successfully, not if I can load it. I I think installing the `tidyverse` already tries to do this to this in some capacity? In both of these instances I believe the package is compiling from source and not using a tarball, so that could affect things as well.

**Comment by gaborcsardi** [comment]
>  if a package was installed successfully, not if I can load it.

How can you decide if an installation was successful? remotes uses install.packages() internally, and that is quite resistant, in that it does not throw errors if dependency installs fail, and in a bunch of other cases. The fact that it quits with a zero exit code does not mean that the package was properly installed  and it is in a useable state. Loading the package seems to be a better test.

R itself tried to load the package, at least for source packages, AFAIR, so there is a built in test.

**Comment by jimhester** [comment]
I think this issue was more about having a diagnostic message, e.g. 'package xyz was successfully installed' that would be easy to grep for.

**Comment by gaborcsardi** [comment]
Yes, but how do you know it was successfully installed?

**Comment by jimhester** [comment]
Yeah I know, it is tricky to do with `install.packages()`. We already have this in pkgman, so I think we can punt on this here.

**Comment by gaborcsardi** [comment]
Btw. there is already a line coming from `install.packages` (probably). E.g.
```
Package '...' has been installed to '...'
```
