### ISSUE TITLE
Fix  `@*release`

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/remotes#200]
```r
❯ install_github("r-lib/R6@*release")
Error in github_resolve_ref.github_release(meta$ref %||% ref, meta, auth_token) :
  No releases found for repo r-lib/R6.
```

**Comment by gaborcsardi** [comment]
So often times people just create tags and not real releases. Quite confusingly these show up here: https://github.com/r-lib/R6/releases

But not here: https://api.github.com/repos/r-lib/R6/releases

In the API, you need to query https://api.github.com/repos/r-lib/R6/tags to get the tags.

remotes currently uses the real releases only. I think it would make sense to use all tags, maybe? 

@jimhester ?

**Comment by jimhester** [comment]
This feature is so rarely known / used I am not sure it is even worth fixing this edge case, it is also somewhat more correct to only use proper releases, although I often forget to make them as well.

**Comment by gaborcsardi** [comment]
Yeah, devtools behaves the same as remotes AFAICT.

**Comment by wlandau** [comment]
For me and my team, it would be extremely valuable to have syntax in `remotes` to get the latest Git tag, regardless of whether a GitHub release actually exists.

@shikokuchuo, @llrs and I are working on [R-releases](https://github.com/r-releases/help), a new project that [began in the R Consortium Repositories Working Group](https://github.com/RConsortium/r-repositories-wg/blob/main/minutes/2024-03-04_Minutes.md). We have lofty ambitions to curate Git releases across the entire R package ecosystem in [one central R-universe](https://github.com/), but we are finding that many maintainers create Git tags without GitHub releases, and that makes things difficult for us. C.f. https://github.com/r-universe-org/help/issues/378

If I understand correctly (@jeroen please correct me if I am wrong), [R-universe uses `remotes` to track references](https://ropensci.org/blog/2021/06/22/setup-runiverse/#pro-tip-tracking-custom-branches-or-releases). So if `remotes` were to adopt notation to track the latest tag, R-universe could pick that up right away.

It would be the most seamless for me and my team if the existing `*release` notation could get tags instead of releases, but I understand if this would be considered a breaking change.

**Comment by wlandau** [comment]
@shikokuchuo pointed out that `*releases` seems to be for GitHub only. So maybe my comment above belongs in a separate issue.

**Comment by wlandau** [comment]
> It would be the most seamless for me and my team if the existing *release notation could get tags instead of releases, but I understand if this would be considered a breaking change (or not entirely correct, as you discussed above).

Actually, we are still discussing whether tags are feasible for our purposes in R-releases at all. So it would be useful to distinguish between latest tag and latest release. I like how the  "*release"  ref currently works.

**Comment by wlandau** [comment]
The concept of a "latest release" makes sense, but I don't think the concept of a "latest tag" makes sense because of the possibility of tags in non-default branches.

https://github.com/r-releases/help/issues/26#issuecomment-1983685871 describes an experiment I did with https://github.com/wlandau/tag-test. The `v1` tag was created in the default branch `main`, and the `v-feature` tag was created in a non-default branch in a commit downstream of `v1`. In https://api.github.com/repos/wlandau/tag-test/tags, `v-feature` takes precedence over `v1` even though it could be unstable from a package release standpoint. 

So on reflection, I completely agree with (and rely on) the current behavior of the `"*release"` reference syntax: just get the latest formal release, ignore tags.

But it would be really nice if this were supported for GitLab: https://github.com/r-lib/remotes/issues/570

**Comment by wlandau** [comment]
> But it would be really nice if this were supported for GitLab: https://github.com/r-lib/remotes/issues/570

Actually, from https://github.com/r-universe-org/help/issues/378#issuecomment-1981986053 this seems to be handled from R-universe directly. So even that is not a `remotes` issue.
