### ISSUE TITLE
`remote_package_name()` and `remote_sha()` should return NA if a branch is deleted

### ISSUE THREAD

**Issue by jimhester** [r-lib/remotes#274]
Right now they 422, which isn't terribly useful and at least in this case we should just always install the package even if the previous branch is deleted.

``` r
remotes:::remote_sha(remotes:::github_remote("tidyverse/purrr@rc-0.3.1"))
#> Error: HTTP error 422.
#>   No commit found for SHA: rc-0.3.1
#> 
#>   Rate limit remaining: 4959/5000
#>   Rate limit reset at: 2019-01-11 19:11:52 UTC
#> 
#> 
```

**Comment by privefl** [comment]
How can we overcome this error for now?

**Comment by fabian-s** [comment]
For everybody else running into this ATM due to `dplyr`, `rlang` etc deleting branches from Github:
run the  `install_github`-command that brough you here with `options(error = recover)`,  check out the offending input to `remote_sha` and re-install that package from CRAN (if available). At least that's what worked for me, see also https://stackoverflow.com/a/54829798
