### ISSUE TITLE
pip freeze and pip install -r equivalents

### ISSUE THREAD

**Issue by riccardopinosio** [r-lib/remotes#360]
Consider the following scenario: working on a local machine I have developed a package that depends on a few other packages, which are listed in imports. Now I want to build a dockerfile which will spin up a docker container and install this package with the exact version of the dependency tree as I had on my original machine.

In python I would do pip freeze, which generates a .txt with the packages currently installed in the environment; I can then use pip install -r to install exactly this version of the packages in the container, downgrading or upgrading packages as necessary.

There doesn't seem a direct equivalent of this operation in R. If I do remotes::install_local it will install the package and the missing dependencies, but it will always install the most recent version of the missing packages, and will upgrade packages if required. Ideally, there would be a function to gather the exact dependency tree of the package (using e.g. local_package_deps) and write them to file, and a function to read such file and install exactly these packages (using e.g. install_version). Opinions on this?

**Comment by cderv** [comment]
If you don't know it yet, you could be interested by [`renv`: Project environments for R](https://github.com/rstudio/renv). This is the replacement of [packrat](https://github.com/rstudio/packrat), that is already filling this usage you described for R. (lock package environement to easily recreate)

This will be the closest you would find to pip freeze or virtual env. There is a function to gather all dependencies in the project, with their version and writing this to a file. You'll get a lockfile describing all the dependencies of your code, with associated package version so that you project package environment is freeze. This lockfile could then be used to restore the same exact environment. 

This new website is also a good reference: https://environments.rstudio.com/

Hope it helps.

**Comment by jimhester** [comment]
As mentioned by @cderv (thanks!) there are other packages to fill this need and I think this is out of scope for remotes, so I will close this issue.
