### ISSUE TITLE
Handling of package dependency constraints

### ISSUE THREAD

**Issue by martinstuder** [r-lib/remotes#376]
Let's assume I have a package with the following package dependencies (using a mix of all of no constraint, `>=`, `>`, `==`, `<=` and `<`):
```
Type: Package
Package: testdeps
Title: Handling Package Dependency Specification
Version: 0.0.1
Authors@R: person("Martin", "Studer", "martin.remo.studer@gmail.com", c("aut", "cre"))
Description: Testing handling of package dependency specifications.
License: MIT
Imports: 
    abind,
    biogas (>= 1.9.0),
    coop (> 0.4-0),
    deal (== 1.2-35),
    effsize (<= 0.7.0),
    face (< 0.1-4)
```

Let's further assume I have the following packages installed:
```
install.packages("remotes")

remotes::install_version("biogas", "1.8.0")
remotes::install_version("coop", "0.4-0")
remotes::install_version("deal", "1.2-37")
remotes::install_version("effsize", "0.7.1")
remotes::install_version("face", "0.1-5")
```
If I run `remotes::install_deps()` for the above `DESCRIPTION` file, the packages `deal`, `effsize` and `face` won't be downgraded to a (most recent?) matching version. In fact, `remotes::install_deps()` asks whether the dependencies should be _upgraded_ although that would violate the package version constraints. Is this the expected behavior?

Surely, package dependency constraints such as `==`, `<=` and `<` are not very common but they are valid and sometimes even useful. I would have expected `remotes::install_deps(...)` to either fail or install a valid set of packages matching the dependency constraints (specifically when using `remotes::install_deps(upgrade = 'never')`).

In a similar way, I think it would be useful to have an option `remotes::install_deps(upgrade = 'if_required')` that would upgrade dependencies only if required, i.e. only when a version of a package is installed that doesn't match the dependency constraint.

**Comment by jimhester** [comment]
`==` `<=` and `<` are 'valid', but there is no code in base R that handles them and it is not something we plan to address in remotes.

In addition because you can only have one version of a particular package loaded pinning a version with `==` breaks down very quickly, as soon as any other package needs a different version the two packages are incompatible.

CRAN only supplies binaries for the latest version of packages and only tests packages with the latest versions, and when dependencies are installed only the latest versions of packages are installed. This makes `<` and `<=` not very useful in practice either.

Because of thIs the only conditions that are actually useful are `>` and `>=`, so these are the primary ones we are going to invest developer time supporting in remotes.

[pak](https://github.com/r-lib/pak) uses a more sophisticated solver to resolve dependencies, and likely supports the other comparisons, if you are interested in this I would suggest you consider that project.

**Comment by martinstuder** [comment]
@jimhester Thanks for your feedback. `pak` looks very interesting - I'm definitely going to have a closer look.

**Comment by lunfel** [comment]
Why would `==` `<=` and `<` be valid if not used anywhere and do not plan to be implemented? I feel like this honestly brings only confusion to users. I was relying on those to lock my dependencies to a certain version to make my R application reproductible on another machine (trying to follow same best practices from php's composer and JavaScript's npm/yarn lock files)

**Comment by jimhester** [comment]
@lufel please look into the [renv](https://github.com/rstudio/renv) package, it is aimed at the usage you describe.

**Comment by stefanoborini** [comment]
@jimhester as far as I know, renv just recreates an environment. It does not ensure that the constraints are respected, especially when the full tree is concerned. In fact, I developed AstraZeneca/roo exactly for this reason.

**Comment by king-of-poppk** [comment]
> @jimhester as far as I know, renv just recreates an environment. It does not ensure that the constraints are respected, especially when the full tree is concerned. In fact, I developed [AstraZeneca/roo](https://github.com/AstraZeneca/roo) exactly for this reason.

@stefanoborini `renv` maintains a separate package library where it installs dependencies.  `renv::snapshot()` and `renv::restore()` allow to have a reproducible library using `renv.lock`. What does `roo` add?
