### ISSUE TITLE
custom remote types

### ISSUE THREAD

**Issue by dseynaev** [r-lib/remotes#509]
Is there a way to implement custom remote types e.g. by implementing an `install_*()` in a third-party package?

My apologies if this has been asked before or is mentioned somewhere but I couldn't find anything with a quick search.

**Comment by jimhester** [comment]
No, there is not currently a way to do this.

In order to support it the internal S3 generic methods would have to be exported.

https://github.com/r-lib/remotes/blob/77202734c6f690022c10ce8d8916527bbd2ad865/R/install-remote.R#L155-L160

And the lookup at https://github.com/r-lib/remotes/blob/77202734c6f690022c10ce8d8916527bbd2ad865/R/deps.R#L499-L500 would have to change in order to support custom remotes in external packages.
