### ISSUE TITLE
Request: Enable source refs by default

### ISSUE THREAD

**Issue by wch** [r-lib/remotes#540]
Very often when I install a package using remotes, I want to keep source refs, because I want to be able to debug the package, or see the code for profiling. I think source refs used to be enabled at default at some point in the past, though I could be wrong about that.

Figuring out the incantation each time for this is nontrivial. Try to think of how to do it.
.
.
.
.
Hint: `"--with-keep.source"`
.
.
.
.
Another hint: `INSTALL_opts`

It would be very helpful if it were enabled by default. Or, at the very least, if examples for it were given in the documentation for `install_github` or `install_local`.

**Comment by jimhester** [comment]
I would suggest putting `R_KEEP_PKG_SOURCE=yes` in your `.Renviron` file to do this.

**Comment by jimhester** [comment]
Unfortunately code with source references has non-negligible overhead in the R interpreter, even when byte compiled, which is why it is not turned on by R by default.

Because of this I don't think it is something we could set for people automatically by default, even though I agree it does make the debugging experience nicer, which is why I have had `R_KEEP_PKG_SOURCE=yes` set for many years now.

**Comment by wch** [comment]
It would be nice if there were an option like `R_KEEP_PKG_SOURCE=yes`, but it only affected packages installed by remotes. On Linux, for example, where the packages are all installed from source, it would make all packages have source refs, but I'm usually interested in source refs only for the packages installed using devtools and friends.

Anyway, at the very least, having an example with `INSTALL_opts="--with-keep.source"` would be very helpful.
