### ISSUE TITLE
Syntax for gitlab remote in DESCRIPTION file

### ISSUE THREAD

**Issue by wolski** [r-lib/remotes#552]
If at all an issue than about documentation.

I would like to add to the DESCRIPTION file  `Remotes:`  

a package I am installing like this:

```
remotes::install_gitlab("wolski/prolfquaData", host="gitlab.bfabric.org")
```

and I fail to infer the correct syntax based on that documentation in the [Devtools dependencies](https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html)

vignette.

**Comment by jimhester** [comment]
For the Remotes syntax it is not possible to use non-standard hosts, on either GitHub or GitLab, it is only for the cloud hosted repositories.

However as a workaround you can use either the URL remote for the tarball or a git remote for the git repo.

**Comment by statnmap** [comment]
Concerning GitLab, you cannot use the `git:` or `url:` when your repo is private because the function will not look for `GITLAB_PAT` and you will not have the permission to download.  
That would be nice if the host could be deduced from this `gitlab::git@domain.com/repo/name` for instance. With default to "GitLab.com" as now.
