### ISSUE TITLE
GitHub Deploy Key (as opposed to PAT) support?

### ISSUE THREAD

**Issue by mmuurr** [r-lib/remotes#553]
Is there any plan to support SSH-key-based access to GitHub repos for `install_github(...)`, as opposed to using PATs? The use case in particular would be for a build process to fetch an R package from a GitHub repository, where access is controlled _at the repository-level_ via a [GitHub Deploy Key](https://docs.github.com/en/free-pro-team@latest/developers/overview/managing-deploy-keys#deploy-keys). This helps prevent the need to generate a pseudo-user (just to create a PAT) that can then be shared across an ops & development team (as deploy scripts shouldn't have to run as any specific _actual_ (i.e. human) user).

**Comment by jimhester** [comment]
No, but you can use `install_git()` with a SSH endpoint instead of `install_github()`.

Developing good software requires relentless focus, which means that we have to say no to many good ideas.

Even though we're closing this issue, we really appreciate the feedback, and hope you'll continue to contribute in the future :smile:
