### ISSUE TITLE
install package "as"

### ISSUE THREAD

**Issue by MyKo101** [r-lib/remotes#583]
Would it be feasible or out of scope for remotes functions to be able to install packages with different names? i.e. rename a package while installing it.

This could be done by adding an "as" parameter to the various `install_()` functions.

The particular use-case would be if a user wants to compare two versions of the same package, you could install one version with a different name.

This would be similar to `import ... as ...` in python, but work at the installation step, rather than the loading step.

I believe for the majority of packages, this would simply require editing the DESCRIPTION file during install, but may be more complicated for binaries, etc...

**Comment by gaborcsardi** [comment]
You can't reliably rename a package while installing it.

**Comment by jimhester** [comment]
Thanks for filing this issue! Unfortunately, we need to restrict the functions in remotes to only be those required directly to install packages. It would also be tricky to do what you propose robustly because most packages need more than just the name changed in the DESCRIPTION to install.

Developing good software requires relentless focus, which means that we have to say no to many good ideas.

Even though we're closing this issue, we really appreciate the feedback, and hope you'll continue to contribute in the future :smile:

**Comment by MyKo101** [comment]
Rather serendipitously, the `box` package has now been added to CRAN which allows users to do this. I'm posting this here in case someone happens to come across this thread while searching for a solution to the problem of loading packages with different names (although unlikely).

GH link: [https://github.com/klmr/box](https://github.com/klmr/box)
CRAN: [https://cran.r-project.org/web/packages/box/index.html](https://cran.r-project.org/web/packages/box/index.html)

**Comment by gaborcsardi** [comment]
@MyKo101 Interesting, can you show an example? I can't seem to find this in the box README or docs.

**Comment by MyKo101** [comment]
@gaborcsardi. So my example was focused on using different versions of the same package with aliases, but the intention was for a general use of renaming packages as with `import ... as ...` in Python. Currently, `{box}` doesn't explicitly imply the use of different versions of the same package, however I could see this being an implementation in the future.

Currently, it is easy to _load_ a package with a different name using something like:
```
box::use(tb = tibble)
tb$tibble(x=1:10)
```

Sorry for my early enthusiasm. It isn't _quite_ what I was wanting when I posted this Issue, but it does allow for a _lot_ of what I was thinking it could be used for.

**Comment by gaborcsardi** [comment]
> Currently, it is easy to load a package with a different name using something like:

I am fairly sure that this does not work when loading multiple versions of the same package, at least for packages with compiled code, because both packages will use the same shared library, leading to crashes or undefined behavior. E.g. if I install an older version of tibble in a separate library:

```
❯ R -q -e 'packageVersion("tibble")'
> packageVersion("tibble")
[1] ‘3.0.6’

❯ R -q -e '.libPaths("/tmp/lib2"); packageVersion("tibble")'
> .libPaths("/tmp/lib2"); packageVersion("tibble")
[1] ‘3.0.0’
```

and then use box to load both under different names:

```r
loadNamespace("box")
.libPaths(c("/tmp/lib2", .libPaths()))
.libPaths()
"tibble" %in% loadedNamespaces()
box::use(oldtb = tibble)
grep("tibble", sapply(.dynLibs(), "[[", "path"), value = TRUE)
environment(oldtb$tibble)$.__NAMESPACE__.$path

# remove /tmp/lib2
.libPaths(.libPaths()[-1])
.libPaths()
box::use(tb = tibble)
tail(.dynLibs(), 1)
environment(tb$tibble)$.__NAMESPACE__.$path
```

Will give me this:

```
❯ R -q -f box.R
> loadNamespace("box")
<environment: namespace:box>
> .libPaths(c("/tmp/lib2", .libPaths()))
> .libPaths()
[1] "/private/tmp/lib2"
[2] "/Users/gaborcsardi/Library/R/4.0/library"
[3] "/Library/Frameworks/R.framework/Versions/4.0/Resources/library"
> "tibble" %in% loadedNamespaces()
[1] FALSE
> box::use(oldtb = tibble)
> grep("tibble", sapply(.dynLibs(), "[[", "path"), value = TRUE)
[1] "/private/tmp/lib2/tibble/libs/tibble.so"
> environment(oldtb$tibble)$.__NAMESPACE__.$path
[1] "/private/tmp/lib2/tibble"
>
> # remove /tmp/lib2
> .libPaths(.libPaths()[-1])
> .libPaths()
[1] "/Users/gaborcsardi/Library/R/4.0/library"
[2] "/Library/Frameworks/R.framework/Versions/4.0/Resources/library"
> box::use(tb = tibble)
> tail(.dynLibs(), 1)
                                 Filename Dynamic.Lookup
1 /private/tmp/lib2/tibble/libs/tibble.so          FALSE
> environment(tb$tibble)$.__NAMESPACE__.$path
[1] "/private/tmp/lib2/tibble"
```

As you can see, both `oldtb` and `tb` use the same shared object file, loaded from `/tmp/lib2`. The other shared object file was not loaded. Actually, `tb` just uses the same package as `oldtb`, box never loaded the new version of the package, as the internal `$path` shows.

R uses a bunch of global structures for loaded package information, and it is really hard to load two versions of the same package. pak does this for a couple of packages, i.e. it loads them "privately", without affecting the list of "officially loaded packages", it looks like this: https://github.com/r-lib/pak/blob/49bcef90aa5a48ef0b822d79cae54203acc8673e/R/subprocess.R#L132

But this does not work for packages with S3 (and probably S4) classes, because they need to register their methods in a global table.
